### ISSUE TITLE
Checkbox layout and TouchUI

### ISSUE THREAD

**Issue by yet-another-average-joe** [OllisGit/OctoPrint-DryRun#1]
Hello, and thanks for this new plugin.

The checkbox needs more vertical spacing ! 

![dry_run](https://user-images.githubusercontent.com/43514870/55635665-8ef16480-57c1-11e9-9a10-dab0b1d1a69c.PNG)

**Comment by OllisGit** [comment]
I tested several UI Designs:
![image](https://user-images.githubusercontent.com/24205767/57180927-da189900-6e8d-11e9-939f-0084806903db.png)
![image](https://user-images.githubusercontent.com/24205767/57180930-dd138980-6e8d-11e9-8c5b-e50b44ee3a73.png)

But the simplest approach (and hopefully most usable) is to add more space if TouchUI is enabled.
![image](https://user-images.githubusercontent.com/24205767/57180959-37144f00-6e8e-11e9-944e-26cf7764c3db.png)

Please check the new Version 1.0.3 and give me a feedback.

BR
Olli

**Comment by yet-another-average-joe** [comment]
Hello !

I cannot test on my real printe (only one, and running most of the time)r, so , for testing purpose, I use a dedicated Pi with everything installed + virtual printer plugin, and VNC viewer in order to emulate a real printer.

First test with 1.0.3 does not work. Layout is broken : in the browser (TouchUI interface) and in VNC with emulated local LCD, the check box is displayed over the cooldown button (top right corner). Clicking anywhere in the buttons (Pause Stop or Cooldown) checks/unchecks Dryrun, IF these buttons are inactive. If Pause and Stop buttons are active (while printing), DryRun button is still over the Cooldown button, but under the 2 others

Not printing :

Top Z-order : DryRun button
Pause, Stop, Cooldown buttons

While printing

Top Z order : Pause, Stop buttons
Dryrun
Cooldown

(Z order : Windows API vocabulary. With LInux, I don't know how to call it ; it's relative to the windows overlapping / painting from bottom to top, and to the mouse focus)

![Capture](https://user-images.githubusercontent.com/43514870/57194615-2379ee80-6f49-11e9-83c1-978ce0d059fa.PNG)


[EDIT] the design with the icon is the nicest !

**Comment by OllisGit** [comment]
@yet-another-average-joe  It was not easy, but I made it!

I hired a CSS-Expert, because in the TouchUI-Theme the layout has a lot of "hard-positionings".

The new Version 1.1.0 looks like this:
![image](https://user-images.githubusercontent.com/24205767/57795659-d666fb00-7746-11e9-9767-ace3994cd917.png)

Please test it in your environment and give me a feedback.

CYa,
Olli

**Comment by yet-another-average-joe** [comment]
Thanks !

Seems to work flawlessly (on the real printer with the real LCD).

Possible enhancement : while dry printing, it is possible to toggle the buttons. It seems to have no effect, but it is confusing. Disabling them would be better.

**Comment by OllisGit** [comment]
Thanks for your feedback.

So I also thought about disabling the dry run button, but then I thought it is a useful feature. 
Start print -> heating -> activate dry run. Now you have a heated print without extrusion...no idea that someone need this feature, but it is there.

If you have other concerns, please a new issue.

BR
Olli
