### ISSUE TITLE
Check box under another plug in button

### ISSUE THREAD

**Issue by bhmyers66** [OllisGit/OctoPrint-DryRun#3]
The checkbox for dry run is under the button for the preheat plug in. This is new since the latest upgrade to 
![dryrun](https://user-images.githubusercontent.com/50296695/57195334-de3cc900-6f16-11e9-98a1-f08d445eccf3.jpg)

**Comment by OllisGit** [comment]
@bhmyers66  Sorry for that! 
The last version should optimize the TouchUI-Theme and not destroying the normal one.
I will fix this in the next version.
In the meantime you could install the previous version manualy: 

Settings/PluginManager:
https://github.com/OllisGit/OctoPrint-DryRun/archive/1.0.2.zip

**Comment by bhmyers66** [comment]
> @bhmyers66 Sorry for that!
> The last version should optimize the TouchUI-Theme and not destroying the normal one.
> I will fix this in the next version.
> In the meantime you could install the previous version manualy:
> 
> Settings/PluginManager:
> https://github.com/OllisGit/OctoPrint-DryRun/archive/1.0.2.zip

No worries.

**Comment by OllisGit** [comment]
New Version 1.1.0 looks like this and fixed the problem
![image](https://user-images.githubusercontent.com/24205767/57795749-08785d00-7747-11e9-82ce-e91882dfec61.png)
