### ISSUE TITLE
BUG: UI refreshing. (F5)

### ISSUE THREAD

**Issue by njozsef** [OllisGit/OctoPrint-DryRun#4]
Hi
I use Dryrun and Themefly plugin, fantastic tool for testing, but after pressed the f5 or reopen the octoprint site, dryrun status is lost.
video: f5 pressed at 12 sec.
https://drive.google.com/open?id=1RkU4w8vyYynP7ILtV8w1kVqg3iIrNNbU
I tested plugin without themefly. result: lost dryrun status too.

thank you

**Comment by OllisGit** [comment]
@njozsef 
Thanks a lot to point me to this big issue.
It is now fixed in the newest Version 1.1.1

Please test and give me a feedback.
BR
Olli

**Comment by OllisGit** [comment]
No feedback -> closed!

**Comment by njozsef** [comment]
Thank you OllisGit.
Sorry for noreply.
