### ISSUE TITLE
New buttons Z-order and TouchUI

### ISSUE THREAD

**Issue by yet-another-average-joe** [OllisGit/OctoPrint-DryRun#5]
Hello,

There's a bug with the buttons Z-order. Have a look to these captures :

OctoPrint 1.3.11 / TouchUI 0.3.13 / Dry Run 1.1.1 / 7" HDMI Touch LCD display

![Capture1](https://user-images.githubusercontent.com/43514870/59851234-644c8c00-936c-11e9-8d57-600706b1aab6.PNG)

![Capture2](https://user-images.githubusercontent.com/43514870/59851242-6adb0380-936c-11e9-9258-8665b8ef3f33.PNG)

This glitch is visible with OctoPrint+TouchUI activated in a browser, on the LCD, and in VNC (the captures come from VNC)

This is really weird.

It does not occur on another Pi with OctoPrint 1.3.11 / TouchUI 0.3.13 / Dry Run 1.1.1
The only difference is that the 2nd Pi is headless, with a virtual printer (minimalist testing rig)

**Comment by OllisGit** [comment]
I couldn't reproduced the bug with TouchUI 0.3.12, but with TouchUI 0.3.13.
I will prepare a new fixed version the next couple of days.

BR
Olli

**Comment by yet-another-average-joe** [comment]
Great !

**Comment by OllisGit** [comment]
Hi @yet-another-average-joe , new version 1.1.2 is out.

Please test it in your environment and give me a feedback.

Thx, in advance
Olli

**Comment by yet-another-average-joe** [comment]
Works fine, on 2 systems, with local display, remote display (VNC) and in the browser.

Thanks !

I close the issue.
