### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fgugliuzza** [OllisGit/OctoPrint-DryRun#6]
The plugin can't be enabled when OctoPrint 1.4.0 is running on Python 3, because it is not reported as compatible. I think it could be ported to Python 3 with relative ease, by wrapping a filter() call with list() and at most a couple of other modifications.

I tried doing this myself but when I install via zip file OctoPrint incorrectly reports plugin name as "(Unknown)" and doesn't show it in the plugin list.

Any idea on how to install the plugin on Python 3 systems?

**Comment by OllisGit** [comment]
Hi @fgugliuzza ,

how did you zip the plugin? You need to zip from the root folder. 
As minimum it must include setup.py, requirements.txt and the octoprint_DryRun - folder.

Then everything should be deployable.

Or just attach your zip-file, then I can verify the file.

BR
Olli

**Comment by OllisGit** [comment]
Hi @fgugliuzza ,

btw. I am using the gcode-testmode from Octolaps, thats the reason why I ask the author to fix the py3-issue.
See https://github.com/FormerLurker/Octolapse/issues/525

**Comment by fgugliuzza** [comment]
Hi! Sorry for the delay in the reply, I was very busy these days.
Anyway, I made the zip from the root folder as you said and attached it here [master-python3.zip](https://github.com/OllisGit/OctoPrint-DryRun/files/4671981/master-python3.zip). The only modifications to the code are the python 3 "flags" for OctoPrint in `__init__.py`:
`__plugin_pythoncompat__ = ">=2.7,<4"`
and a wrap of filter() using list() in `gcode_parser.py` (that I have yet to test, though):
`                if any(list(filter(parameters.has_key, additional_parameters.keys()))):`
I'm still getting the Unknown plugin name message, and I've attached it too as an image.
![immagine](https://user-images.githubusercontent.com/26921815/82733706-02cc3480-9d16-11ea-8760-ab2d19529912.png)

I've performed all this on Windows, could it be the cause? Maybe the zip or some permissions get corrupted?

**Comment by OllisGit** [comment]
Hi @fgugliuzza ,
I just take a short look to your plugin:
- I installed your zip on my system. 
- I have the same popup. Ignore it. This is an OctoPrint-Issue.
- But your plugin is not working, because in Pyhon3 the import-statements looks different.
Error-Message:
```
/OctoPrint/octoprint_latest/venv-3/lib/python3.6/site-packages/octoprint_DryRun/gcode_parser.py", line 26, in <module>
    import utility
ModuleNotFoundError: No module named 'utility'
```
Correct-Statement
```
from octoprint_DryRun import utility
```

I didn't looked into your list-change in detail, but you need to replace the ```has_key``` statement, it is not available any more (https://docs.python.org/3.1/whatsnew/3.0.html#builtins)  

You can also look into my solution (see Octolaps-Issue for more details)

**Comment by OllisGit** [comment]
I released a new Version 1.2.0.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by fgugliuzza** [comment]
I just installed it and run a dry print. It works great!
Thank you very much for your time!

Best regards
Francesco

**Comment by OllisGit** [comment]
You'r welcome!
